apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-nestjs-microservice-andrejschefer-role
rules:
- apiGroups: ["apps", "extensions"] # "" indicates the core API group
  resources: ["pods", "deployments", "services"]  
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
