apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: demo-nestjs-microservice-andrejschefer-rolebinding
subjects:
- kind: ServiceAccount
  name: azure-developer
roleRef:
  kind: Role
  name: demo-nestjs-microservice-andrejschefer-role
  apiGroup: rbac.authorization.k8s.io
